//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpleoEF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string dni { get; set; }
        public int idCargo { get; set; }
        public int salario { get; set; }
    
        public virtual Cargo Cargo { get; set; }
    }
}
